services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - TLC_DOCKER_IMAGE=guardrails-tlc
      - TLC_SHARED_DIR=/app/tla-output
      - TLC_DOCKER_VOLUME=guardrails-tla-output
      - TLC_CONTAINER_WORKDIR=/workspace
      - TLC_DOCKER_CONTEXT=/workspace-host/docker/tlc
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
    volumes:
      - tla-output:/app/tla-output
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace-host:ro
    networks:
      - app-network

volumes:
  tla-output:
    name: guardrails-tla-output

networks:
  app-network:
    driver: bridge
